### ISSUE TITLE
[应用代理]: 测试代理

### ISSUE THREAD

**Issue by YkeLit** [YkeLit/test-proxy#10]
### Project name

pasdo-khor

### Server ip address

10.1.1.1

### Server port

443

### Middlewares

```yaml
customRequestHeaders:
  X-Script-Name: "test"
  X-Script-Nae: "tes"
customResponseHeaders:
  X-Custom-Response-Header: "value"
  Access-Control-Allow-Origin: "*"
  Access-Controla-Allow-Methods: "PUT, GET, POST"
```
