### ISSUE TITLE
[应用代理]: 新建应用代理

### ISSUE THREAD

**Issue by YkeLit** [YkeLit/test-proxy#11]
### Project name

new-app-pro

### Server ip address

10.1.1.1

### Server port

443

### Middlewares

```yaml
customRequestHeaders:
  X-Script-Name: "test"
  X-Script-Nae: "tes"
```
