### ISSUE TITLE
[应用代理]: pr 测试

### ISSUE THREAD

**Issue by YkeLit** [YkeLit/test-proxy#14]
### Project name

pr-esa

### Server ip address

10.1.1.5

### Server port

4434

### Middlewares

```yaml
customRequestHeaders:
  X-Script-Name: "test"
  X-Script-Nae: "tes"
```
