### ISSUE TITLE
[应用代理]:  测试项目

### ISSUE THREAD

**Issue by YkeLit** [YkeLit/test-proxy#7]
### Project name

proxy-esqaa

### Server ip address

1.1.12.1

### Server port

443

### Middlewares

```yaml
customRequestHeaders:
  X-Script-Name: "test"
  X-Script-Nae: "tes"
customResponseHeaders:
  X-Custom-Response-Header: "value"
  Access-Control-Allow-Origin: "*"
  Access-Controla-Allow-Methods: "PUT, GET, POST"
```
