### ISSUE TITLE
[应用代理]: 新建代理

### ISSUE THREAD

**Issue by YkeLit** [YkeLit/test-proxy#9]
### Project name

new-proxy-ac

### Server ip address

1.1.1.4

### Server port

445

### Middlewares

```yaml
customRequestHeaders:
  X-Script-Name: "test"
  X-Script-Nae: "tes"
  Access-Controla-Allow-Methods: "PUT, GET, POST"
```
